config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'
  devise_for :users
  resources :events,   except: [:destroy] do
      resources :bookings, only: [:new, :create,:index]
    end
  resources :categories
  resources :profiles
  resources :photos, only: [:destroy]
  get "about" => "pages#about"
  get "contact" => "pages#contact"
  # get "user" => "users#show"
  get "search" => "pages#index"
  namespace :api do
    resources :events, except: [:edit,:new]
    resources :categories
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user, optional: :true
  has_and_belongs_to_many :categories
  has_many :photos, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :visitors, through: :bookings, source: :user

  validates :name, presence: true, length: { maximum: 50}
  validates :description, presence: true, length: { maximum:500 }
  validates :size, presence: true
  validates :location, presence: true
  validates :price, presence: true
  # validates :starts_at, presence: true
  # validates :ends_at, presence: true
  BARGAIN_PRICE = 30

  def validate_user?(user)
    user_id == user.id
  end

  def self.order_by_price
    order(price: :asc )
  end
  def self.outdoor_booked


  end
  def self.outdoor_count
     Event.joins(:categories).where(:categories => { :name=>"outdoor" }).sum(:size)
  end
  def self.need_sort(search)
    case search
    when "Name Ascending"
      order(name: :asc)
    when "Name Descending"
      order(name: :desc)
    when "Size Ascending"
      order(size: :asc )
    when "Size Descending"
      order(size: :desc )
    else
      order(name: :asc)
    end
  end
  def bargain?
    price < BARGAIN_PRICE
  end
  private
  def check_user?
    current_user.id == true
  end
end

app/controllers/api/events_controller.rb
class Api::EventsController < ApplicationController
  skip_before_action :verify_authenticity_token
  def index
    render status: 200, json: {
      events: Event.all
    }.to_json
  end

  def show
  event = Event.find(params[:id])

  render status: 200, json: {
    event: event
  }.to_json
  end

  def create
    event = Event.new(event_params)

    if event.save
      render status: 201, json: {
        event: event
      }.to_json
    else
      render status: 422, json: {
        errors: event.errors
      }.to_json
    end
  end

  def update
    event = Event.find(params[:id])
    if event.update(event_params)
      render status: 200, json: {
        message: "Event successfully updated",
        room: event
      }.to_json
    else
       render status: 422, json: {
        message: "The event could not be updated",
        errors: event.errors
      }.to_json
    end
  end

  def destroy
    event = Event.find(params[:id])
    event.destroy
    render status: 200, json: {
      message: "Event successfully deleted"
    }.to_json
  end

  private
  def event_params
    params
    .require(:event)
    .permit(
      :name, :size, :description, :location, :image_url, :includes_drinks,
      :includes_food,  :active, :price
    )
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update]
  before_action :all_categories, only: [ :edit, :update]
  before_action :authenticate_user!, except: [:show]

  def index
    @events = current_user.events
  end

  def show
    if current_user
      @valid_user = @event.validate_user?(current_user)
    end
  end

  def new
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      image_params.each do |image|
        @event.photos.create(image: image)
      end
      redirect_to @event, notice: "Event created"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @event.update(event_params)
      image_params.each do |image|
        @event.photos.create(image: image)
      end
      redirect_to @event, notice: "Event updated"
    else
      render :edit
    end
  end


  private

  def set_event
    @event = Event.find(params[:id])
    @owner = User.find(@event.user_id)
    @photos = @event.photos
    @categories = @event.categories
  end
  def all_categories
    @categories = Category.all
  end
  def event_params
    params
    .require(:event)
    .permit(
      :name, :size, :description, :location, :image_url, :includes_drinks,
      :includes_food, :starts_at, :ends_at, :active, :price, category_ids: []
    )
  end
  def image_params
    params[:images].present? ? params.require(:images) : []
  end



end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= render 'validationerrors' %>

<%= form_for @event, html: { multipart: true } do |f| %>
  <div class="form-group">
    <%= f.label :name %><br />
    <%= f.text_field :name, class: "form-control", autofocus: true,placeholder: 'Name your event', autocomplete: "off" %>
  </div>

  <div class="form-group">
    <%= f.label :location %>
    <%= f.text_field :location, autocomplete: "off",placeholder: 'Fill in a location',class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price, autocomplete: "off",placeholder: 'How much will it cost',class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :size %><br />
    <%= f.number_field :size, autocomplete: "off",placeholder: 'How many people can attend',class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description, autocomplete: "off",placeholder: 'What is going to happen',class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url, autocomplete: "off",placeholder: 'link a relevant image',class: "form-control" %>
  </div>
  <h4> Is the Event going on as planned</h4>
  <div class="field">
    <%= f.label :active %> <%= f.check_box :active %>
  </div>
  <h4> Amnities</h4>

  <div class="field">
    <%= f.label :includes_food %> <%= f.check_box :includes_food %>
    <%= f.label :includes_drinks %> <%= f.check_box :includes_drinks %>
  </div>
  <h4>Categories</h4>


  <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |b| %>
    <div class="form-group">
      <%= b.check_box(class: "check_box") %> <%= b.object.name %>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :starts_at %><br />
    <%= f.date_field :starts_at, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :ends_at %><br />
    <%= f.date_field :ends_at, class: "form-control" %>
  </div>
  <label>Photos</label>

  <div class="form-group">
    <span class="btn btn-default">
      Upload Photos
      <%= file_field_tag "images[]", type: :file, multiple: true %>
    </span>
  </div>

  <br />
  <div class="actions">
    <%= f.submit (@event.new_record? ? "Create" : "Update"), class: "btn btn-primary" %>
  </div>
  <div id="photos">
  <%= render 'photos/list' %>
</div>

<% end %>

app/views/events/_validationerrors.html.erb
<ul>
  <% @event.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>

app/views/events/bookevent.html.erb
<h1>Booking for <%= @event.name%></h1>

<%= form_for @booking do |b|%>
  <div class="form-group">
    <%= b.label :group_size%><br/>
    <%= b.number_field :group_size, class: "form-control", autofocus: true,placeholder: 'fill in size of your group', autocomplete: "off"   %>
  </div>
  <div class="actions">
    <%= b.submit  "Createbooking", class: "btn btn-primary" %>
  </div>
<%end%>

app/views/events/edit.html.erb
<h1> Edit Event</h1>

<%=render "form" %>

app/views/events/index.html.erb
<h1 class="text-center rows"> Events organized by you:</h1>
<div class="col-md-12 ">
  <% @events.each do |event| %>
    <div class="col-md-4 panel panel-default">
            <%= link_to event.name, event_path(event.id), class: "double_size" %>
    <%= image_tag event.image_url, class: "foreground_image" %>

     <p><%= event.description %></p>
    </div>
    <%end%>
</div>
<br>
<div class="col-md-12 text-center double_size">
<%= link_to "New event", new_event_path, class:"btn btn-primary "%>
</div>

app/views/events/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-1">

<h2>New event</h2>

  <%= render "form" %>


</div>
</div>

app/views/events/show.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2 text-center panel panel-default">
    <h1><%= @event.name %></h1><br>
    <h4> The event will run from <%=@event.starts_at.strftime("%Y - %B - %d") %> until <%=@event.ends_at.strftime("%Y - %B - %d") %> hosted by <%=  @owner.full_name %></h4>
    <%= image_tag @event.image_url, class: "foreground_image" %>
    <p> <%= @event.description%><br> Price is <%= @event.price%></p>
    <% if @event.includes_drinks && @event.includes_food %>
      <p> Drinks and food are included</p>
    <% elsif @event.includes_drinks %>
      <p> Drinks are included</p>
    <% elsif @event.includes_food %>
      <p> Foods is included</p>
    <% else %>
      <p> Drinks and food are not included</p>
    <% end %>
    <% @event.categories.each do |category| %>
      <%= link_to category.name, category_path(category.id), class:"btn btn-default" %>
    <% end %>
    <br>
    <% if current_user
      if @valid_user %>
        <%=link_to "Edit event", edit_event_path, class:"btn btn-primary" %><br>
        <%= link_to "Delete", event_path(@event.id), method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-danger"%>
      <%else%>
        <%=render "/bookings/form"%>
      <%end
    else %>
      <%= link_to "Log in", new_user_session_path, class:"btn btn-primary"%>
      <%= link_to "No account? Sign up now!", new_user_registration_path, class:"btn btn-danger btn-extended"%>
    <%end%>


  </div>
    <div class="rows col-md-12 panel panel-default">
  <h4>Photos</h4>

    <% @event.photos.each do |photo| %>
    <div class="panel panel-default col-md-4">
      <div class="panel-heading">
      <%= image_tag photo.image, class:"thumbnail"%>
    </div></div>
    <% end %>
  </div>
</div>