config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'
  devise_for :users
  resources :events,   except: [:destroy] do
      resources :bookings, only: [:new, :create,:index]
    end
  resources :categories
  resources :profiles
  resources :photos, only: [:destroy]
  get "about" => "pages#about"
  get "contact" => "pages#contact"
  # get "user" => "users#show"
  get "search" => "pages#index"
  namespace :api do
    resources :events, except: [:edit,:new]
    resources :categories
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :event
  validates :group_size, presence: true, numericality: {less_than_or_equal_to: 3,  only_integer: true}

  def total_price
    self.price * self.group_size
  end
  def self.booking_count
    count
  end
  def self.outdoor_booked
    Event.joins(:categories).joins(:bookings).where(:categories => { :name=>"outdoor" }).sum(:group_size)
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :events
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user, optional: :true
  has_and_belongs_to_many :categories
  has_many :photos, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :visitors, through: :bookings, source: :user

  validates :name, presence: true, length: { maximum: 50}
  validates :description, presence: true, length: { maximum:500 }
  validates :size, presence: true
  validates :location, presence: true
  validates :price, presence: true
  # validates :starts_at, presence: true
  # validates :ends_at, presence: true
  BARGAIN_PRICE = 30

  def validate_user?(user)
    user_id == user.id
  end

  def self.order_by_price
    order(price: :asc )
  end
  def self.outdoor_booked


  end
  def self.outdoor_count
     Event.joins(:categories).where(:categories => { :name=>"outdoor" }).sum(:size)
  end
  def self.need_sort(search)
    case search
    when "Name Ascending"
      order(name: :asc)
    when "Name Descending"
      order(name: :desc)
    when "Size Ascending"
      order(size: :asc )
    when "Size Descending"
      order(size: :desc )
    else
      order(name: :asc)
    end
  end
  def bargain?
    price < BARGAIN_PRICE
  end
  private
  def check_user?
    current_user.id == true
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :event

  mount_uploader :image, ImageUploader
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  validates :first_name, presence: true, length: { maximum: 50}
  validates :last_name, presence: true, length: { maximum: 50}
  validates :bio, presence: true, length: { maximum: 500}


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :bookings, dependent: :destroy
  has_many :booked_events, through: :bookings, source: :event
  has_many :events, dependent: :destroy
  has_one :profile, dependent: :destroy
  def full_name
    if self.profile
     "#{self.profile.first_name} #{self.profile.last_name}"
   else
     self.email
   end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_event, only: [:new,:create]
  before_action :authenticate_user!
  def index

  end

  def new
    @booking = current_user.bookings.build
  end

  def create
    @booking = current_user.bookings.build(booking_params.merge({event: @event, price: @event.price}))
    if @booking.save
      redirect_to event_path(@event.id), notice: "Booking created"
    else
    end
  end

  private
  def set_event
    @event = Event.find(params[:event_id])
  end
  def booking_params
    params.require(:booking).permit( :group_size)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update]
  before_action :all_categories, only: [ :edit, :update]
  before_action :authenticate_user!, except: [:show]

  def index
    @events = current_user.events
  end

  def show
    if current_user
      @valid_user = @event.validate_user?(current_user)
    end
  end

  def new
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      image_params.each do |image|
        @event.photos.create(image: image)
      end
      redirect_to @event, notice: "Event created"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @event.update(event_params)
      image_params.each do |image|
        @event.photos.create(image: image)
      end
      redirect_to @event, notice: "Event updated"
    else
      render :edit
    end
  end


  private

  def set_event
    @event = Event.find(params[:id])
    @owner = User.find(@event.user_id)
    @photos = @event.photos
    @categories = @event.categories
  end
  def all_categories
    @categories = Category.all
  end
  def event_params
    params
    .require(:event)
    .permit(
      :name, :size, :description, :location, :image_url, :includes_drinks,
      :includes_food, :starts_at, :ends_at, :active, :price, category_ids: []
    )
  end
  def image_params
    params[:images].present? ? params.require(:images) : []
  end



end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @lastthreevents = Event.last(3)
    # @events = Event.all
    random_event
    @booking_count = total_bookings_made
    @outdoor_remaining = outdoor_spot_count - outdoor_booked
  end

  def index
    @search = params[:search]
    @events = Event.where('name ILIKE ?',"%#{@search.strip}%")
    @events.need_sort(params[:search_by])
  end
  private
  def random_event
    @random = Event.order("RANDOM()").first
  end
  def total_bookings_made
    Booking.booking_count
  end
  def outdoor_spot_count
    Event.outdoor_count
  end
  def outdoor_booked
    Booking.outdoor_booked
  end
  def need_sorting
    Event.need_sort
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def destroy
    photo = Photo.find(params[:id])
    @event = photo.event
    if @event.user.id == current_user.id
      photo.destroy
      redirect_to edit_event_path(@event), notice: "Photo successfully removed"
    else
      redirect_to @event, notice: "Cannot delete that photo"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show;
    @events = current_user.events
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head class= "head">
    <title>CodaisseurUp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/_sorting.html.erb
<%= link_to "Name ascending",search_path(search_by: "Name Ascending",search: @search), class:"button"%>
<%= link_to "Name descending",search_path(search_by: "Name Descending",search: @search), class:"button"%>
<%= link_to "Size created ascending",search_path(search_by: "Size Ascending",search: @search), class:"button"%>
<%= link_to "Size descending",search_path(search_by: "Size Descending",search: @search), class:"button"%>

app/views/pages/about.html.erb
<h1> Not blank</h1>

app/views/pages/contact.html.erb
<h1> Not blank</h1>

app/views/pages/home.html.erb
<div class = "col-md-12 text-center">
  <h1>CodaisseurUp</h1>

  <img src = "http://res.muenchen-p.de/.imaging/stk/responsive/galleryPreview980/dms/va-2017/tollwood-2017/teaser/tollwood-2017-hp-01/document/tollwood-2017-hp-01.jpg" class= "background_image"/>

  <div class = "tophome rows ">
<div class=" col-md-8">
    <br>
    <p class="double_size text-center ">
      <%= image_tag @random.image_url, class: "foreground_image stretch_image" %>
      <h3><%= @random.name%></h3>
    <p> <%= @random.description%> <br>price is <%= @random.price%> Euro</p>
    <%= link_to "More", event_path(@random.id) ,class: "btn btn-default"%>
    </div>
<br><br><br>
<div class=" col-md-4 panel">
  <p>Total bookings made: <%= @booking_count  %></p>
  <p>Outdoor events space remaining: <%= @outdoor_remaining%></p>
</div>
</div>

<br>
<div class= "row">
  <div class= "col-md-12 text-center "><h2>Current Events</h2>
    <h4> Events starting in the next few weeks</h4>
  </div>
    <% @lastthreevents.each do |event| %>
  <div class= "col-md-4 ">
      <%= image_tag event.image_url, class: "foreground_image" %>
      <h3><%= event.name%></h3>
    <p> <%= event.description%> <br>price is <%= event.price%> Euro</p>
    <%= link_to "More", event_path(event.id) ,class: "btn btn-default"%>
  </div>
<% end%>
</div>
<br><br>

<div class="row blue">
  <div class= "col-md-12 text-center ">
    <img src = "http://res.muenchen-p.de/.imaging/stk/responsive/galleryPreview980/dms/va-2017/tollwood-2017/teaser/tollwood-2017-hp-01/document/tollwood-2017-hp-01.jpg" class= "foreground_image"/>
  <div class="col-md-6 text-center">
    <h3>Look for an event</h3>
    <p> There are a lot of niche events, something for everyone</p>

    <%= form_tag("/search", method: "get") do %>
      <%= label_tag(:search, "Search for:") %>
      <%= text_field_tag :search, params[:search], placeholder: "enter event name"%>
      <%= submit_tag("Search",class:"btn btn-primary")  %>
    <% end %>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<h1> Search results</h1>
<div class="row col-md-12 text-center">
<% @events.each do |event|%>
<div class="col-md-4 ">
<%= image_tag event.image_url, class: "foreground_image" %>
  <%= link_to event.name, event_path(event.id) %>
 <p><%= event.description %></p>
</div>
<%end%>
</div>
<%= render "sorting" %>

app/views/pages/show.html.erb
<h1> Search results</h1>
<div class="row col-md-12 text-center">
<% @events.each do |event|%>
<div class="col-md-4 ">
<%= image_tag event.image_url, class: "foreground_image" %>
  <%= link_to event.name, event_path(event.id) %>
 <p><%= event.description %></p>
</div>
<%end%>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "CodaisseurUp", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
          <li> <%= link_to "About", about_path %></li>
          <li> <%= link_to "Contact", contact_path %></li>
        <% if !user_signed_in? %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path, class: "btn btn-default btn-extended" %></li>
        <% else %>
          <li class="dropdown">

            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.full_name  %> <span class="caret"></span></a>

            <ul class="dropdown-menu">
              <li><%= link_to "Edit Password", edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <%if current_user.profile %>
              <li><%= link_to "Edit Profile", edit_profile_path(current_user.id) %></li>
              <li role="separator" class="divider"></li>
              <%else%>
              <li><%= link_to "Create profile", new_profile_path(current_user.id) %></li>
              <li role="separator" class="divider"></li>
              <% end%>
              <li><%= link_to "Organized Events", events_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Attending Events",  profile_path(current_user.id) %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>