config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'
  devise_for :users
  resources :events,   except: [:destroy] do
      resources :bookings, only: [:new, :create,:index]
    end
  resources :categories
  resources :profiles
  resources :photos, only: [:destroy]
  get "about" => "pages#about"
  get "contact" => "pages#contact"
  # get "user" => "users#show"
  get "search" => "pages#index"
  namespace :api do
    resources :events, except: [:edit,:new]
    resources :categories
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :event

  mount_uploader :image, ImageUploader
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def destroy
    photo = Photo.find(params[:id])
    @event = photo.event
    if @event.user.id == current_user.id
      photo.destroy
      redirect_to edit_event_path(@event), notice: "Photo successfully removed"
    else
      redirect_to @event, notice: "Cannot delete that photo"
    end
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_list.html.erb
<% if @photos %>
<div class="row col-md-12">
  <% @photos.each do |photo| %>
    <div class="panel panel-default col-md-4">
      <div class="panel-heading">
        <%= image_tag photo.image, class: "thumbnail" %>
      </div>
      <div class="panel-body">
        <span><%= link_to "Delete", photo_path( photo.id ), class: "btn btn-default", method: :delete, data: { confirm: "Are you sure?" } %></span>
      </div>
    </div>
  <% end %>
</div>

<% end %>