config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'
  devise_for :users
  resources :events,   except: [:destroy] do
      resources :bookings, only: [:new, :create,:index]
    end
  resources :categories
  resources :profiles
  resources :photos, only: [:destroy]
  get "about" => "pages#about"
  get "contact" => "pages#contact"
  # get "user" => "users#show"
  get "search" => "pages#index"
  namespace :api do
    resources :events, except: [:edit,:new]
    resources :categories
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :events
end

app/controllers/api/categories_controller.rb
class Api::CategoriesController < ApplicationController
  skip_before_action :verify_authenticity_token
  def index
    render status: 200, json: {
      categories: Category.all
    }.to_json
  end
  def show
  category = Category.find(params[:id])

  render status: 200, json: {
    categories: category
  }.to_json
  end

  def create
    category = Category.new(category_params)

    if category.save
      render status: 201, json: {
        category: category
      }.to_json
    else
      render status: 422, json: {
        errors: category.errors
      }.to_json
    end
  end
  private
  def category_params
    params
    .require(:category)
    .permit(
      :name, :description)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update]
  def index
    @categories = Category.all
  end
  def show ;  end
  def new
    @category = Category.new
  end
  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category, notice: "Category created"
    else
      render :new
    end
  end

  def edit ;  end
  def update
    if @category.update(category_params)

      redirect_to @category, notice: "category updated"
    else
      render :edit
    end
  end
  private
  def set_category
    @category = Category.find(params[:id])
  end
  def category_params
    params
    .require(:category)
    .permit(
      :name, :description)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= render 'validationerrors' %>

<%= form_for @category do |f| %>
<div class="form-group">
  <%= f.label :name %><br />
  <%= f.text_field :name, class: "form-control", autofocus: true,placeholder: 'Name your category', autocomplete: "off" %>
</div>
<div class="field">
  <%= f.label :description %><br />
  <%= f.text_field :description, autocomplete: "off",placeholder: 'what is it for',class: "form-control" %>
</div>
<div class="actions">
  <%= f.submit (@category.new_record? ? "Create" : "Update"), class: "btn btn-primary" %>
</div>
<%end%>

app/views/categories/_validationerrors.html.erb
<ul>
  <% @category.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>

app/views/categories/edit.html.erb
<h1> Edit <%= @category.name %></h1>
<%= render "form" %>

app/views/categories/index.html.erb
<h4>Themes</h4>
<% @categories.each do |category| %>
  <span class="btn btn-default"><%= link_to category.name, category_path(category.id) %></span>
<% end %>
<br><br>
<br>

<%= link_to "New category", new_category_path, class:"btn btn-danger"%>

app/views/categories/new.html.erb
<%= render "form" %>

app/views/categories/show.html.erb
<h1> <%= @category.name %></h1>
<p> <%= @category.description%></p>
<div class="btn btn-default"> <%= link_to "Edit", edit_category_path(@category.id) %></div>
<br><br><br><br>
<div class="btn btn-danger"><%= link_to "All categories", categories_path%></div>